
seleniumhub:
  image: selenium/hub
  ports:
  - 4444:4444
  
chrome:
  image: selenium/node-chrome
  links:
  - seleniumhub:hub
  environment:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - GRID_BROWSER_TIMEOUT=300
  - GRID_TIMEOUT=720
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

